version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_USER_NAME: ${MONGO_USER_NAME}
      MONGO_USER_PASSWORD: ${MONGO_USER_PASSWORD}
      MONGO_DATABASE_NAME: ${MONGO_DATABASE_NAME}
    ports:
      - 37017:27017
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./db:/data/db
  #app:
    #build: .
    #ports:
     # - "3000:3000"
