version: "3.7"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      AUTH_DB_USER_NAME: ${AUTH_DB_USER_NAME}
      AUTH_DB_USER_PASSWORD: ${AUTH_DB_USER_PASSWORD}
      AUTH_DB_NAME: ${AUTH_DB_NAME}
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./db:/data/db