version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "cars"
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  #app:
    #build: .
    #ports:
    #  - 3000:3000
    #environment:
     # MONGO_ADDRESS: "mongo"
      #MONGO_PORT: 27017
      #MONGO_DATABASE_NAME: "cars"
     # NODE_ENV: "production"
      #GLOBAL_PORT: 3000

