version: "3.9"

#https://www.datanovia.com/en/lessons/docker-compose-wait-for-container-using-wait-tool/docker-compose-wait-for-mongodb-container-to-be-ready/
# documentation on the wait, to ensure the DB is ready before we start the app
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "cars"
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  app:
    build: .
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    command: sh -c "/wait && yarn start"
    links:
      - mongodb
    environment:
      MONGO_ADDRESS: "mongodb"
      MONGO_PORT: 27017
      MONGO_DATABASE_NAME: "cars"
      NODE_ENV: "production"
      GLOBAL_PORT: 3000
      WAIT_HOSTS: mongodb:27017
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
      WAIT_HOST_CONNECT_TIMEOUT: 30

